name: payment-service

services:
  postgres-db:
    image: postgres:18
    container_name: payment-service-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

    ports:
      - "${DB_PORT}:5432"

    volumes:
      - payment-service-data:/var/lib/postgresql

volumes:
  payment-service-data:
    external: true
